const CSS = [
  '.frp { display: flex; flex-direction: column; gap: 14px; color: var(--dsw-alias-label-primary, inherit); font-size: 13px; }',
  '.frp-card { background: var(--dsw-alias-bg-layer-1, transparent); border: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.25)); border-radius: 10px; padding: 12px 14px; }',
  '.frp-title { font-size: 15px; font-weight: 600; margin: 0 0 6px; }',
  '.frp-muted { color: var(--dsw-alias-label-secondary, rgba(128,128,128,.9)); }',
  '.frp-code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; background: var(--dsw-alias-bg-layer-2, rgba(128,128,128,.08)); border-radius: 6px; padding: 2px 6px; word-break: break-all; }',
  '.frp-up { display: flex; flex-direction: column; gap: 8px; }',
  '.frp-dot { width: 9px; height: 9px; border-radius: 50%; flex: none; }',
  '.frp-dot-up { background: var(--dsw-alias-state-success-primary, #34d399); }',
  '.frp-dot-cooling { background: var(--dsw-alias-state-warn-primary, #fbbf24); }',
  '.frp-dot-degraded { background: var(--dsw-alias-state-warn-primary, #fbbf24); }',
  '.frp-dot-off { background: var(--dsw-alias-border-l2, rgba(128,128,128,.5)); }',
  '.frp-name { font-weight: 600; font-size: 13.5px; }',
  '.frp-tag { font-size: 11px; border: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.3)); border-radius: 5px; padding: 0 6px; color: var(--dsw-alias-label-secondary, inherit); }',
  '.frp-btn { font: inherit; font-size: 12px; border: 1px solid var(--dsw-alias-border-l2, rgba(128,128,128,.4)); background: transparent; color: inherit; border-radius: 7px; padding: 3px 10px; cursor: pointer; }',
  '.frp-btn:hover { background: var(--dsw-alias-bg-layer-2, rgba(128,128,128,.1)); }',
  '.frp-btn:disabled { opacity: .45; cursor: default; }',
  '.frp-btn-primary { border-color: var(--dsw-alias-brand-primary, currentColor); }',
  '.frp-input { font: inherit; font-size: 12px; background: var(--dsw-alias-bg-layer-2, rgba(128,128,128,.08)); color: inherit; border: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.3)); border-radius: 7px; padding: 4px 8px; width: 210px; }',
  '.frp-input-wide { width: 100%; box-sizing: border-box; }',
  '.frp-a { color: var(--dsw-alias-brand-primary, inherit); text-decoration: none; }',
  '.frp-a-sm { font-size: 12px; }',
  '.frp-a:hover { text-decoration: underline; }',
  '.frp-stats { font-size: 11.5px; color: var(--dsw-alias-label-secondary, rgba(128,128,128,.9)); line-height: 1.6; }',
  '.frp-err { color: var(--dsw-alias-state-error-primary, #f87171); font-size: 12px; white-space: pre-wrap; word-break: break-all; }',
  '.frp-warn { color: var(--dsw-alias-state-warn-primary, #fbbf24); font-size: 12px; white-space: pre-wrap; word-break: break-all; }',
  '.frp-ok { color: var(--dsw-alias-state-success-primary, #34d399); font-size: 12px; }',
  '.frp-models { display: flex; flex-direction: column; max-height: 300px; overflow: auto; }',
  '.frp-mrow { display: flex; align-items: center; gap: 9px; padding: 8px 2px; cursor: pointer; border-bottom: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.12)); white-space: nowrap; overflow: hidden; }',
  '.frp-mrow:hover { background: var(--dsw-alias-bg-layer-2, rgba(128,128,128,.06)); }',
  '.frp-models > div:last-child .frp-mrow, .frp-models > div:last-child .frp-mdetail { border-bottom: none; }',
  '.frp-mdetail { display: flex; flex-direction: column; gap: 5px; padding: 8px 2px 12px 13px; border-bottom: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.12)); font-size: 12px; }',
  '.frp-mk { color: var(--dsw-alias-label-secondary, rgba(128,128,128,.9)); display: inline-block; min-width: 52px; }',
  '.frp-prow-solo:only-child { border-bottom: none; }',
  '.frp-keyrow { display: flex; gap: 8px; align-items: flex-start; }',
  '.frp-keyrow .frp-input { flex: 1; min-width: 0; width: auto; box-sizing: border-box; }',
  '.frp-keytoggle { flex: none; align-self: flex-start; margin-top: 1px; display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 26px; padding: 0; }',
  '.frp-eye { display: block; }',
  '.frp-keymask { flex: 1; min-width: 0; box-sizing: border-box; display: inline-flex; align-items: center; font: inherit; font-size: 12px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; letter-spacing: 1.5px; color: var(--dsw-alias-label-secondary, inherit); background: var(--dsw-alias-bg-layer-2, rgba(128,128,128,.08)); border: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.3)); border-radius: 7px; padding: 6px 9px; cursor: pointer; user-select: none; min-height: 26px; }',
  '.frp-keymask:hover { border-color: var(--dsw-alias-border-l2, rgba(128,128,128,.5)); }',
  '.frp-hiddenrow { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; padding: 10px 2px 12px; font-size: 12px; }',
  '.frp-hiddenchip { font-size: 12px; }',
  '.frp-pre { margin: 0; padding: 8px 10px; border-radius: 7px; background: var(--dsw-alias-bg-layer-2, rgba(128,128,128,.08)); border: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.2)); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; line-height: 1.6; overflow: auto; }',
  '.frp-model-id { font-family: ui-monospace, Menlo, monospace; font-size: 12px; }',
  // ---- 原生风格：头部 / 开关 / 供应商列表（点击展开）----
  '.frp-head { display: flex; flex-direction: column; gap: 4px; }',
  '.frp-headrow { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }',
  '.frp-headtitle { font-size: 16px; font-weight: 600; margin: 0; }',
  '.frp-headspace { flex: 1; }',
  '.frp-headline { font-size: 12px; display: flex; flex-wrap: wrap; row-gap: 2px; }',
  '.frp-headline span { word-break: break-all; }',
  '.frp-input[readonly] { opacity: .7; cursor: default; }',
  '.frp-switch { display: inline-flex; align-items: center; gap: 7px; cursor: pointer; user-select: none; position: relative; }',
  '.frp-switch input { position: absolute; opacity: 0; width: 0; height: 0; }',
  '.frp-slider { width: 32px; height: 17px; border-radius: 999px; background: var(--dsw-alias-bg-layer-3, rgba(128,128,128,.35)); position: relative; transition: background .15s; flex: none; }',
  ".frp-slider:after { content: ''; position: absolute; width: 13px; height: 13px; border-radius: 50%; top: 2px; left: 2px; background: var(--dsw-alias-bg-base, #fff); transition: transform .15s; box-shadow: 0 1px 2px rgba(0,0,0,.3); }",
  '.frp-switch input:checked + .frp-slider { background: var(--dsw-alias-brand-primary, rgba(64,128,255,.85)); }',
  '.frp-switch input:checked + .frp-slider:after { transform: translateX(15px); }',
  '.frp-switch input:focus-visible + .frp-slider { outline: 2px solid currentColor; outline-offset: 2px; }',
  '.frp-switch input:disabled + .frp-slider { opacity: .45; }',
  '.frp-switchtext { font-size: 12px; color: var(--dsw-alias-label-secondary, inherit); }',
  '.frp-plist { padding: 2px 12px; }',
  '.frp-prow { display: flex; align-items: center; gap: 9px; padding: 11px 2px; cursor: pointer; border-bottom: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.15)); }',
  '.frp-prow:hover { background: var(--dsw-alias-bg-layer-2, rgba(128,128,128,.06)); }',
  '.frp-plist > div:last-child .frp-prow, .frp-plist > div:last-child .frp-pdetail { border-bottom: none; }',
  '.frp-pname { font-weight: 500; white-space: nowrap; }',
  '.frp-pctl { display: inline-flex; align-items: center; gap: 3px; flex: none; }',
  '.frp-iconbtn { padding: 2px 6px; line-height: 1; }',
  '.frp-pmeta { margin-left: auto; color: var(--dsw-alias-label-secondary, rgba(128,128,128,.9)); font-size: 12px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; padding-left: 12px; }',
  ".frp-chev { color: var(--dsw-alias-label-secondary, rgba(128,128,128,.9)); transition: transform .15s; flex: none; font-size: 14px; }",
  '.frp-chev-open { transform: rotate(90deg); }',
  '.frp-pdetail { display: flex; flex-direction: column; gap: 10px; padding: 8px 2px 14px 23px; border-bottom: 1px solid var(--dsw-alias-border-l1, rgba(128,128,128,.15)); }',
  '.frp-drow { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }',
  '.frp-keyarea { flex: 1; min-width: 220px; width: auto; resize: vertical; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }',
  '.frp-btn-ghost { border-color: transparent; color: var(--dsw-alias-label-secondary, inherit); }',
  '.frp-check { display: inline-flex; align-items: center; gap: 4px; font-size: 12px; }',
  '.frp-form-row { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }',
  // 页签条与面板：视觉与交互对齐宿主「设置 -> 插件」页（下划线页签 + aria + 方向键）。
  '.frp-tabpage { max-width: 720px; color: var(--dsw-alias-label-primary, inherit); flex-direction: column; gap: 12px; display: flex; }',
  '.frp-tabs { border-bottom: 1px solid var(--dsw-alias-border-l2, rgba(128,128,128,.3)); align-items: flex-end; gap: 22px; margin-top: 2px; display: flex; }',
  '.frp-tab { color: var(--dsw-alias-label-tertiary, rgba(128,128,128,.9)); font: inherit; cursor: pointer; background: 0 0; border: 0; padding: 7px 1px 9px; font-size: 13px; line-height: 20px; position: relative; }',
  '.frp-tab:hover, .frp-tab[data-active=true] { color: var(--dsw-alias-label-primary, inherit); }',
  '.frp-tab[data-active=true]:after, .frp-tab:focus-visible:after { background: var(--dsw-alias-label-primary, currentColor); content: ""; border-radius: 2px 2px 0 0; height: 2px; position: absolute; bottom: -1px; left: 0; right: 0; }',
  '.frp-tab:focus-visible { outline: 2px solid var(--dsw-alias-state-business-primary, currentColor); outline-offset: 2px; color: var(--dsw-alias-label-primary, inherit); border-radius: 2px; }',
  '.frp-panel { min-width: 0; padding-top: 2px; }',
  // 原模型页包裹层：不生成盒子，让内置 section 直接参与 frp-tabpage 布局。
  '.frp-models-scope { display: contents; }'
].join('\n')

